; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = arduino_nano_esp32

[env:arduino_nano_esp32]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = arduino_nano_esp32
framework = arduino, espidf
lib_compat_mode = off
lib_deps =
    adafruit/Adafruit NeoPixel@^1.10.6
upload_protocol = esptool
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_NANO_ESP32
    ; -D ARDUINO_VARIANT=\"arduino_nano_esp32\"
    

[env:ota]
extends = env:arduino_nano_esp32
upload_protocol = espota
; Set this to your device IP or mDNS name when uploading OTA.
upload_port = scoreboard.local